### ISSUE TITLE
Livepreview broken data stream

### ISSUE THREAD

**Issue by mritzco** [joergmlpts/olympus-wifi#1]
Thanks for the amazing package!

I'm having an issue with LivePreview, it works well but after a while I get: `broken data stream when reading image file`. 
Seems like 1 frame once in a while fails and the preview gets frozen.

OS: Linux Mint

Would there be a way to make it more reliable? Maybe just drop bad frames and move to next?

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/itzco/anaconda3/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/itzco/anaconda3/lib/python3.9/tkinter/__init__.py", line 814, in callit
    func(*args)
  File "/home/itzco/Projects/github/olympus-wifi/liveview.py", line 312, in check_update_image
    img = self.next_image()
  File "/home/itzco/Projects/github/olympus-wifi/liveview.py", line 299, in next_image
    tmp = ImageTk.PhotoImage(data=jpeg_and_extension.jpeg)
  File "/home/itzco/anaconda3/lib/python3.9/site-packages/PIL/ImageTk.py", line 128, in __init__
    self.paste(image)
  File "/home/itzco/anaconda3/lib/python3.9/site-packages/PIL/ImageTk.py", line 174, in paste
    im.load()
  File "/home/itzco/anaconda3/lib/python3.9/site-packages/PIL/ImageFile.py", line 288, in load
    raise_oserror(err_code)
  File "/home/itzco/anaconda3/lib/python3.9/site-packages/PIL/ImageFile.py", line 72, in raise_oserror
    raise OSError(msg)
OSError: broken data stream when reading image file

```

I tried 
- basic: Try / Except to just ignore Exception but gets worse; 
- `ImageFile.LOAD_TRUNCATED_IMAGES = True` is a popular answer but I don't think it applies

Thanks

**Comment by joergmlpts** [comment]
I could not reproduce the issue but a possible fix has been checked in. The function should now catch the exception, wait for the next frame and try again.

Thanks

**Comment by mritzco** [comment]
Thank you very much, that was extremely fast.

I'll update and check if the issue is resolved

**Comment by mritzco** [comment]
It works perfectly now! 

The frames get delayed but there are no errors.

Thanks so much!
